/*
 * Namsor
 * <h2>NamSor SDK infers Gender and Origin from international names</h2>  <p>NamSor specialized data mining software recognizes the <strong>gender</strong>, the <strong>linguistic or cultural origin of personal names</strong> in any alphabet / language, with fine grain and high accuracy.</p>  <p>Visit <a href=\"http://namsor.com\">NamSor.com</a> to learn more.</p> 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.namsor.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Model for Output Names
 */
@ApiModel(description = "Model for Output Names")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-05-28T14:22:58.421+02:00")
public class OutputNameForOrigin {
  @SerializedName("country")
  private String country = null;

  @SerializedName("countryAlt")
  private String countryAlt = null;

  @SerializedName("countryFirstName")
  private String countryFirstName = null;

  @SerializedName("countryLastName")
  private String countryLastName = null;

  @SerializedName("countryName")
  private String countryName = null;

  @SerializedName("firstName")
  private String firstName = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("lastName")
  private String lastName = null;

  @SerializedName("region")
  private String region = null;

  @SerializedName("score")
  private Float score = null;

  @SerializedName("scoreFirstName")
  private Float scoreFirstName = null;

  @SerializedName("scoreLastName")
  private Float scoreLastName = null;

  @SerializedName("script")
  private String script = null;

  @SerializedName("subRegion")
  private String subRegion = null;

  @SerializedName("topRegion")
  private String topRegion = null;

  public OutputNameForOrigin country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  @ApiModelProperty(required = true, value = "")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public OutputNameForOrigin countryAlt(String countryAlt) {
    this.countryAlt = countryAlt;
    return this;
  }

   /**
   * Get countryAlt
   * @return countryAlt
  **/
  @ApiModelProperty(value = "")
  public String getCountryAlt() {
    return countryAlt;
  }

  public void setCountryAlt(String countryAlt) {
    this.countryAlt = countryAlt;
  }

  public OutputNameForOrigin countryFirstName(String countryFirstName) {
    this.countryFirstName = countryFirstName;
    return this;
  }

   /**
   * Get countryFirstName
   * @return countryFirstName
  **/
  @ApiModelProperty(value = "")
  public String getCountryFirstName() {
    return countryFirstName;
  }

  public void setCountryFirstName(String countryFirstName) {
    this.countryFirstName = countryFirstName;
  }

  public OutputNameForOrigin countryLastName(String countryLastName) {
    this.countryLastName = countryLastName;
    return this;
  }

   /**
   * Get countryLastName
   * @return countryLastName
  **/
  @ApiModelProperty(value = "")
  public String getCountryLastName() {
    return countryLastName;
  }

  public void setCountryLastName(String countryLastName) {
    this.countryLastName = countryLastName;
  }

  public OutputNameForOrigin countryName(String countryName) {
    this.countryName = countryName;
    return this;
  }

   /**
   * Get countryName
   * @return countryName
  **/
  @ApiModelProperty(value = "")
  public String getCountryName() {
    return countryName;
  }

  public void setCountryName(String countryName) {
    this.countryName = countryName;
  }

  public OutputNameForOrigin firstName(String firstName) {
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public OutputNameForOrigin id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public OutputNameForOrigin lastName(String lastName) {
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public OutputNameForOrigin region(String region) {
    this.region = region;
    return this;
  }

   /**
   * Get region
   * @return region
  **/
  @ApiModelProperty(value = "")
  public String getRegion() {
    return region;
  }

  public void setRegion(String region) {
    this.region = region;
  }

  public OutputNameForOrigin score(Float score) {
    this.score = score;
    return this;
  }

   /**
   * Get score
   * @return score
  **/
  @ApiModelProperty(value = "")
  public Float getScore() {
    return score;
  }

  public void setScore(Float score) {
    this.score = score;
  }

  public OutputNameForOrigin scoreFirstName(Float scoreFirstName) {
    this.scoreFirstName = scoreFirstName;
    return this;
  }

   /**
   * Get scoreFirstName
   * @return scoreFirstName
  **/
  @ApiModelProperty(value = "")
  public Float getScoreFirstName() {
    return scoreFirstName;
  }

  public void setScoreFirstName(Float scoreFirstName) {
    this.scoreFirstName = scoreFirstName;
  }

  public OutputNameForOrigin scoreLastName(Float scoreLastName) {
    this.scoreLastName = scoreLastName;
    return this;
  }

   /**
   * Get scoreLastName
   * @return scoreLastName
  **/
  @ApiModelProperty(value = "")
  public Float getScoreLastName() {
    return scoreLastName;
  }

  public void setScoreLastName(Float scoreLastName) {
    this.scoreLastName = scoreLastName;
  }

  public OutputNameForOrigin script(String script) {
    this.script = script;
    return this;
  }

   /**
   * Get script
   * @return script
  **/
  @ApiModelProperty(value = "")
  public String getScript() {
    return script;
  }

  public void setScript(String script) {
    this.script = script;
  }

  public OutputNameForOrigin subRegion(String subRegion) {
    this.subRegion = subRegion;
    return this;
  }

   /**
   * Get subRegion
   * @return subRegion
  **/
  @ApiModelProperty(value = "")
  public String getSubRegion() {
    return subRegion;
  }

  public void setSubRegion(String subRegion) {
    this.subRegion = subRegion;
  }

  public OutputNameForOrigin topRegion(String topRegion) {
    this.topRegion = topRegion;
    return this;
  }

   /**
   * Get topRegion
   * @return topRegion
  **/
  @ApiModelProperty(value = "")
  public String getTopRegion() {
    return topRegion;
  }

  public void setTopRegion(String topRegion) {
    this.topRegion = topRegion;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OutputNameForOrigin outputNameForOrigin = (OutputNameForOrigin) o;
    return Objects.equals(this.country, outputNameForOrigin.country) &&
        Objects.equals(this.countryAlt, outputNameForOrigin.countryAlt) &&
        Objects.equals(this.countryFirstName, outputNameForOrigin.countryFirstName) &&
        Objects.equals(this.countryLastName, outputNameForOrigin.countryLastName) &&
        Objects.equals(this.countryName, outputNameForOrigin.countryName) &&
        Objects.equals(this.firstName, outputNameForOrigin.firstName) &&
        Objects.equals(this.id, outputNameForOrigin.id) &&
        Objects.equals(this.lastName, outputNameForOrigin.lastName) &&
        Objects.equals(this.region, outputNameForOrigin.region) &&
        Objects.equals(this.score, outputNameForOrigin.score) &&
        Objects.equals(this.scoreFirstName, outputNameForOrigin.scoreFirstName) &&
        Objects.equals(this.scoreLastName, outputNameForOrigin.scoreLastName) &&
        Objects.equals(this.script, outputNameForOrigin.script) &&
        Objects.equals(this.subRegion, outputNameForOrigin.subRegion) &&
        Objects.equals(this.topRegion, outputNameForOrigin.topRegion);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, countryAlt, countryFirstName, countryLastName, countryName, firstName, id, lastName, region, score, scoreFirstName, scoreLastName, script, subRegion, topRegion);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OutputNameForOrigin {\n");
    
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    countryAlt: ").append(toIndentedString(countryAlt)).append("\n");
    sb.append("    countryFirstName: ").append(toIndentedString(countryFirstName)).append("\n");
    sb.append("    countryLastName: ").append(toIndentedString(countryLastName)).append("\n");
    sb.append("    countryName: ").append(toIndentedString(countryName)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    region: ").append(toIndentedString(region)).append("\n");
    sb.append("    score: ").append(toIndentedString(score)).append("\n");
    sb.append("    scoreFirstName: ").append(toIndentedString(scoreFirstName)).append("\n");
    sb.append("    scoreLastName: ").append(toIndentedString(scoreLastName)).append("\n");
    sb.append("    script: ").append(toIndentedString(script)).append("\n");
    sb.append("    subRegion: ").append(toIndentedString(subRegion)).append("\n");
    sb.append("    topRegion: ").append(toIndentedString(topRegion)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

