/*
 * Namsor
 * <h2>NamSor SDK infers Gender and Origin from international names</h2>  <p>NamSor specialized data mining software recognizes the <strong>gender</strong>, the <strong>linguistic or cultural origin of personal names</strong> in any alphabet / language, with fine grain and high accuracy.</p>  <p>Visit <a href=\"http://namsor.com\">NamSor.com</a> to learn more.</p> 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.namsor.api;

import com.namsor.ApiException;
import com.namsor.model.OutputNameForGender;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GenderApi
 */
@Ignore
public class GenderApiTest {

    private final GenderApi api = new GenderApi();

    
    /**
     * To genderize one name
     *
     * To genderize one name, for example John Smith. Passing a country ISO2 code for local context is optional but helps improve precision.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void extractGenderTest() throws ApiException {
        String firstName = null;
        String lastName = null;
        String xChannelSecret = null;
        String xChannelUser = null;
        OutputNameForGender response = api.extractGender(firstName, lastName, xChannelSecret, xChannelUser);

        // TODO: test validations
    }
    
    /**
     * To genderize one name, with the context of a given country ISO2
     *
     * To genderize one name, for example John Smith, passing a country ISO2 code for local context to improve precision.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void extractGenderLocalTest() throws ApiException {
        String firstName = null;
        String lastName = null;
        String countryIso2 = null;
        String xChannelSecret = null;
        String xChannelUser = null;
        OutputNameForGender response = api.extractGenderLocal(firstName, lastName, countryIso2, xChannelSecret, xChannelUser);

        // TODO: test validations
    }
    
}
