/*
 * Namsor
 * <h2>NamSor SDK infers Gender and Origin from international names</h2>  <p>NamSor specialized data mining software recognizes the <strong>gender</strong>, the <strong>linguistic or cultural origin of personal names</strong> in any alphabet / language, with fine grain and high accuracy.</p>  <p>Visit <a href=\"http://namsor.com\">NamSor.com</a> to learn more.</p> 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.namsor.api;

import com.namsor.ApiException;
import com.namsor.model.ExtractGenderListOutput;
import com.namsor.model.NamesListInput;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GenderListApi
 */
@Ignore
public class GenderListApiTest {

    private final GenderListApi api = new GenderListApi();

    
    /**
     * To genderize many names (up to 1000).
     *
     * To genderize a list of names (up to 1000 at a time). For each name, passing a country ISO2 code for local context is optional but helps improve precision.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void extractGenderListTest() throws ApiException {
        String xChannelSecret = null;
        String xChannelUser = null;
        NamesListInput genderizerList = null;
        ExtractGenderListOutput response = api.extractGenderList(xChannelSecret, xChannelUser, genderizerList);

        // TODO: test validations
    }
    
}
