/*
 * Namsor
 * <h2>NamSor SDK infers Gender and Origin from international names</h2>  <p>NamSor specialized data mining software recognizes the <strong>gender</strong>, the <strong>linguistic or cultural origin of personal names</strong> in any alphabet / language, with fine grain and high accuracy.</p>  <p>Visit <a href=\"http://namsor.com\">NamSor.com</a> to learn more.</p> 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.namsor.api;

import com.namsor.ApiException;
import com.namsor.model.OutputNameForOrigin;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OriginApi
 */
@Ignore
public class OriginApiTest {

    private final OriginApi api = new OriginApi();

    
    /**
     * To determin the origin of a name
     *
     * To extract the likely linguistic/cultural origin of a personal name, at the country-level. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void extractOriginTest() throws ApiException {
        String firstName = null;
        String lastName = null;
        String xChannelSecret = null;
        String xChannelUser = null;
        OutputNameForOrigin response = api.extractOrigin(firstName, lastName, xChannelSecret, xChannelUser);

        // TODO: test validations
    }
    
}
