/*
 * Namsor
 * <h2>NamSor SDK infers Gender and Origin from international names</h2>  <p>NamSor specialized data mining software recognizes the <strong>gender</strong>, the <strong>linguistic or cultural origin of personal names</strong> in any alphabet / language, with fine grain and high accuracy.</p>  <p>Visit <a href=\"http://namsor.com\">NamSor.com</a> to learn more.</p> 
 *
 * OpenAPI spec version: 1.1.0
 * Contact: contact@namsor.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.namsor.api;

import com.namsor.ApiException;
import com.namsor.model.OutputParsedName;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ParseApi
 */
@Ignore
public class ParseApiTest {

    private final ParseApi api = new ParseApi();

    
    /**
     * Parse a fullName into firstName, lastName components.
     *
     * Parse a fullName into firstName, lastName components. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void parseNameTest() throws ApiException {
        String fullName = null;
        String xChannelSecret = null;
        String xChannelUser = null;
        OutputParsedName response = api.parseName(fullName, xChannelSecret, xChannelUser);

        // TODO: test validations
    }
    
}
